name: Hello World
author: David Koch
description: "Greet someone and record the time"
inputs:
  who_to_greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The Time of greeting"
runs:
  using: "node16"
  #created with "ncc build index.js" in hello folder
  main: 'dist/index.js'
  # pre does not work in private actions
  pre: "setup"
  pre-if: runner.os == 'linux'
  post: "cleanup"
  post-if: runner.os == 'linux'