name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      # image from docker-hub
      image: node:22.3-alpine3.19
      env:
        API_URL: some-url.com
    steps:
      - name: Log Node a& Os Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL