name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      # image from docker-hub
      image: node:22.3-alpine3.19
      env:
        API_URL: some-url.com
    steps:
      - name: Log Node a& Os Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Create a file
        run: echo 'Some Text' >> text.txt
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: text.txt
      - uses: actions/checkout@v3
      - name: Run a bash Script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Some String"