name: Matrix
on: [push]

jobs:
    node-matrix:
        continue-on-error: ${{ matrix.experimental == true }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14, 15, 16]
                include:
                    # does not override variable combinations, only matches and adds new variables
                    # this adds is-ubuntu=true to ubuntu-latest
                    - os: ubuntu-latest
                      is-ubuntu: true
                    # a new combination (macos-latest + node 15 is created)
                    - os: macos-latest
                      node-version: 15
                    # no match possible, adds experimental-variable to all "original" (6) combinations
                    - experimental: false
                exclude:
                    - os: ubuntu-latest
                      node-version: 14
                    # excludes all ubuntu-latest combinations
                    # - os: ubuntu-latest
            # if any job fails, the other jobs are cancelled when fail-fast is true
            fail-fast: true
            # max-parallel: 3
        runs-on: ${{ matrix.os }}
        steps:
            - if: matrix.experimental == true
              run: exit 1
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v