name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: 'Input Description'
        type: string
        default: 'David'
        required: false
    secrets:
      access-token:
        description: 'Secret description'
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Context
        run: echo '${{ toJson(github) }}'
      - name: Display Input
        run: echo '${{ inputs.name }}'
      - name: Display Secret
        run: echo '${{ secrets.access-token }}'