name: Stale Issues & PRs
on:
    schedule:
        - cron: "0 14 * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
              with:
                stale-issue-message: "This was a triupmh"
                days-before-stale: 1
                days-before-close: 5