name: Status Check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 20
            - name: Step 2
              id: step_2
              run: exit 1
            - name: Runs on Failure of Step 2
              if: failure() && steps.step_2.conclusion == 'failure'
              run: echo "Step 2 failed"
            - name: Runs on any Failure
              if: failure()
              run: echo "Something failed"
            - name: Runs on Success
              # if is not needed here
              if: success()
              run: echo 'it succeded'
            - name: Always Runs
              if: always()
              run: echo 'after all this time'
            - name: Runs on Cancel
              if: cancelled()
              run: echo 'it was cancelled'
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2'